### ISSUE TITLE
Errors in train_opt.pkl

### ISSUE THREAD

**Issue by 0oshowero0** [yanx27/EverybodyDanceNow_reproduce_pytorch#1]
There are some errors in this option file.
`checkpoints_dir='../checkpoints/'` should be `checkpoints_dir='./checkpoints/'` 
and 
`dataroot='../data/target/train'` should be `dataroot='./data/target/train'`

**Comment by seaweiqing** [comment]
Thanks for your comments :)
We will check this part asap.

**Comment by yanx27** [comment]
Thanks for your comments :)
We have change train_opt (and test_opt)  to `./src/config/` for more convenient operation 
If you have any suggestion, please don't hesitate to tell us directly
