### ISSUE TITLE
Generating source/target image is too slow

### ISSUE THREAD

**Issue by 0oshowero0** [yanx27/EverybodyDanceNow_reproduce_pytorch#13]
It seems that the code doesn't use GPU acceleration too much, which makes the process very slow. It takes nearly 3s to generate a single image..

**Comment by Ha0Tang** [comment]
@0oshowero0 have you solved this problem?

**Comment by 0oshowero0** [comment]
> @0oshowero0 have you solved this problem?

I forget since it's really long ago. You can refer to my issue at #18 to see whether is your problem.
