### ISSUE TITLE
Face enhancement process doesn't work

### ISSUE THREAD

**Issue by 0oshowero0** [yanx27/EverybodyDanceNow_reproduce_pytorch#14]
I found that the parameters of this part of code is a little confusing. I can't let it run according to the Readme, since the data path is not consistent in different files.

**Comment by yanx27** [comment]
Thank you for your reminder. We'll improve the code later :)

**Comment by yanx27** [comment]
> I found that the parameters of this part of code is a little confusing. I can't let it run according to the Readme, since the data path is not consistent in different files.

You can try `./face_enhancer/prepare.py`, thanks for you feedback :)

**Comment by benoitoutlook** [comment]
I got:

XXX: ~ /EverybodyDanceNow_reproduce_pytorch$ python ./face_enhancer/prepare.py
Traceback (most recent call last):
  File "./face_enhancer/prepare.py", line 7, in <module>
    face_sync_dir.mkdir(exist_ok=True)
  File "/XXX/pathlib.py", line 1246, in mkdir
    self._accessor.mkdir(self, mode)
  File "/XXX/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '../data/face/ '
XXXX: ~ /EverybodyDanceNow_reproduce_pytorch$ 

Any help is appreciated!

**Comment by ElegantLin** [comment]
Yes, I also met the same problem. I could not find the face folder.
