### ISSUE TITLE
A method to improve performance of make_target & make_source

### ISSUE THREAD

**Issue by 0oshowero0** [yanx27/EverybodyDanceNow_reproduce_pytorch#18]
Hi, when I use make_target.py and make_source.py to generate training label, I found the speed goes down. Recently I reviewed the code and noticed a issue in these two codes.

In line 99 & 100, take make_target.py as an example, it use matplotlib to draw a figure. However, it doesn't clear the figure so that the speed slows down to 20s/it at 10000s pic and crashs at 15000 pics.

There should be a plt.clf() after plt.savefig(). This will promise the speed won't drop :)

**Comment by seaweiqing** [comment]
We also encountered the same problem in the process of code running! Thank you very much for your suggestion, we will polish the code ASAP!
