### ISSUE TITLE
GPU selection

### ISSUE THREAD

**Issue by 0oshowero0** [yanx27/EverybodyDanceNow_reproduce_pytorch#2]
In train_target_images.py and make_source_images.py, there are
`torch.cuda.set_device(0)`
However from the document [https://pytorch.org/docs/0.4.1/cuda.html?highlight=set_device#torch.cuda.set_device](url), we can see that 

> Usage of this function is discouraged in favor of device. In most cases it’s better to use CUDA_VISIBLE_DEVICES environmental variable.

So I believe just use `os.environ['CUDA_VISIBLE_DEVICES'] = '0'` is better.

By the way, in train_opt.pkl there is also a GPU selection option, I believe it's not necessary.

**Comment by seaweiqing** [comment]
Thanks for your advice :)
Since the GPU is shared by our group, thus we need this step for our implementation.

**Comment by yanx27** [comment]
Thanks for your advice :)
We directly use model from https://github.com/CUHKSZ-TQL/EverybodyDanceNow_reproduce_pytorch/tree/master/src/pix2pixHD and it  already defined its GPU selection option in model, so we just use it directly. I think using `os.environ['CUDA_VISIBLE_DEVICES'] = '0' `is better too.
