### ISSUE TITLE
a typeError in step3 

### ISSUE THREAD

**Issue by hanhailangya** [yanx27/EverybodyDanceNow_reproduce_pytorch#20]
hi, i have a problem there.

when i run step3(train_pose2vid.py),an error has been encountered ：

**TypeError: tensor(1.3251, device='cuda:0') has type <class 'torch.Tensor'>, but expected one of: ((<class 'numbers.Real'>,),) for field Value.simple_value**

what can i slove this error?

Does this have anything to do with the version of tensorflow？

thanks

**Comment by yanx27** [comment]
Thank you for your attention to our work. We didn't use tensorflow in the whole code. You may have some problems with pytorch's version. Can you tell us more about the error, and we will let you know if we meet it :)

**Comment by hanhailangya** [comment]
Thank you, it may be due to the version problem, when I delete out the relevant print content, it works
