### ISSUE TITLE
IndexError and ValueError in the  last step make_gif

### ISSUE THREAD

**Issue by hanhailangya** [yanx27/EverybodyDanceNow_reproduce_pytorch#21]
您好！当我在执行最后一步时遇到了如下问题：
![image](https://user-images.githubusercontent.com/37034839/51513798-a8804280-1e47-11e9-84ec-1255e41c44cd.png)
并且提示：
ValueError: Cannot save animation: no writers are available. Please install ffmpeg to save animations.
但是当我安装了 ffmpeg和Imagemagick后还是会报相同的错误，请问有没有好的解决办法？十分感谢！

**Comment by hanhailangya** [comment]
修改配置文件后已解决

**Comment by jackylee1** [comment]
你好，你是如何解决的呢
