### ISSUE TITLE
target video

### ISSUE THREAD

**Issue by deep0learning** [yanx27/EverybodyDanceNow_reproduce_pytorch#25]
In the training phase, the target video would be the same as source video? or different .mp4 ?
can you share the target video as well, please?
Make target pictures
Put target video mv.mp4 in ./data/target/ and run make_target.py, pose.npy will save in ./data/target/, which contain the coordinate of faces (will use in step6).

**Comment by yanx27** [comment]
Thank you for your attention to our work. Source video is the user's video of the action you want to be imitated ( e.g. star video on the internet ), target video is the video of the person you want to migrate to ( e.g. yourself ), all in mp4 format. If you still don't understand, you can look at the bottom result display, the leftmost is the source video, and the rightmost is the person in the target video. When shooting the target video, you only need to do some actions as much as possible ( about 2 minutes, not too fast ).

In addition, target videos are videos of ourselves, so it is not very convenient to share with you. TT
