### ISSUE TITLE
About pose_model.pth!

### ISSUE THREAD

**Issue by coolwangcoolwang** [yanx27/EverybodyDanceNow_reproduce_pytorch#34]
please tell me where can download pose_model.pth with right link! I can't link google-drive! Thanks!

**Comment by seaweiqing** [comment]
Please try to download here: https://drive.google.com/file/d/1DDBQsoZ94N4NRKxZbwyEXt7Tz8KqgS_w/view
If you still have trouble visiting this web, you could provide us with other tools that you can access.

**Comment by coolwangcoolwang** [comment]
Sincere thanks, if you are convenient, would you like provide the way of  BaiduPan or YandexDisk ! Thanks again!

**Comment by seaweiqing** [comment]
https://pan.baidu.com/s/15b1PDUAxUPm3THk0CvfZzQ 
password: a78q
