### ISSUE TITLE
invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number

### ISSUE THREAD

**Issue by Keneyr** [yanx27/EverybodyDanceNow_reproduce_pytorch#48]
Traceback (most recent call last):
  File "train_pose2vid.py", line 147, in <module>
    main()
  File "train_pose2vid.py", line 104, in main
    errors = {k: v.data[0] if not isinstance(v, int) else v for k, v in loss_dict.items()}
  File "train_pose2vid.py", line 104, in <dictcomp>
    errors = {k: v.data[0] if not isinstance(v, int) else v for k, v in loss_dict.items()}
IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number

Anybody meet the same problem?

**Comment by DetectiveLYJ** [comment]
I meet the same problem
I changed `v.data[0]`  to `v.item()` ,and everything is ok

**Comment by ghost** [comment]
Changing `v.data[0]` to `v.item()` didn't fix this error for me (running on Colab)

P.S. Replacing with `v.data.item()` seems to have fixed it (https://github.com/yanx27/EverybodyDanceNow_reproduce_pytorch/issues/102#issuecomment-853745597)
