### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by xuhongbabe** [yanx27/EverybodyDanceNow_reproduce_pytorch#54]
python make_source.py
Has generated 0 picetures
Has generated 100 picetures
Has generated 200 picetures
Bulding VGG19
src/PoseEstimation/network/rtpose_vgg.py:204: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(m.weight, std=0.01)
src/PoseEstimation/network/rtpose_vgg.py:206: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  init.constant(m.bias, 0.0)
src/PoseEstimation/network/rtpose_vgg.py:209: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(self.model1_1[8].weight, std=0.01)
src/PoseEstimation/network/rtpose_vgg.py:210: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(self.model1_2[8].weight, std=0.01)
src/PoseEstimation/network/rtpose_vgg.py:212: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(self.model2_1[12].weight, std=0.01)
src/PoseEstimation/network/rtpose_vgg.py:213: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(self.model3_1[12].weight, std=0.01)
src/PoseEstimation/network/rtpose_vgg.py:214: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(self.model4_1[12].weight, std=0.01)
src/PoseEstimation/network/rtpose_vgg.py:215: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(self.model5_1[12].weight, std=0.01)
src/PoseEstimation/network/rtpose_vgg.py:216: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(self.model6_1[12].weight, std=0.01)
src/PoseEstimation/network/rtpose_vgg.py:218: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(self.model2_2[12].weight, std=0.01)
src/PoseEstimation/network/rtpose_vgg.py:219: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(self.model3_2[12].weight, std=0.01)
src/PoseEstimation/network/rtpose_vgg.py:220: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(self.model4_2[12].weight, std=0.01)
src/PoseEstimation/network/rtpose_vgg.py:221: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(self.model5_2[12].weight, std=0.01)
src/PoseEstimation/network/rtpose_vgg.py:222: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(self.model6_2[12].weight, std=0.01)
Traceback (most recent call last):
  File "make_source.py", line 54, in <module>
    model.load_state_dict(torch.load(weight_name))
  File "/home/zhunan314/.local/lib/python3.6/site-packages/torch/serialization.py", line 303, in load
    return _load(f, map_location, pickle_module)
  File "/home/zhunan314/.local/lib/python3.6/site-packages/torch/serialization.py", line 459, in _load
    magic_number = pickle_module.load(f)
EOFError: Ran out of input

**Comment by seaweiqing** [comment]
Hi, there, please refer to one of the previous issue [#6 ](https://github.com/CUHKSZ-TQL/EverybodyDanceNow_reproduce_pytorch/issues/6)
