### ISSUE TITLE
About the face enhancer

### ISSUE THREAD

**Issue by Lotayou** [yanx27/EverybodyDanceNow_reproduce_pytorch#7]
Glad to see your work, especially the global pose normalization module. I've already added your project link in my repo home page. Please check here: [Lotayou/everybody_dance_now_pytorch](https://github.com/Lotayou/everybody_dance_now_pytorch).

By the way, the face enhancer module looks familiar. I remember seeing these codes somewhere in another repo before but couldn't find the link in README.md. Do you mind adding a reference? Thanks>:D

**Comment by yanx27** [comment]
OK, thank you for your reminding. I hope we can make progress together :)

**Comment by Lotayou** [comment]
Thanks, cheerio:)
