### ISSUE TITLE
About the config of pix2pixHD which didn't use the local generator

### ISSUE THREAD

**Issue by WilliammmZ** [yanx27/EverybodyDanceNow_reproduce_pytorch#83]
The config of the pix2pixHD at train.py, the param 'netG' set to 'global'. In my opinion, it causes that the model only uses the global generator which more like pix2pix not pix2pixHD. I consider the param should be changed to 'local' for use both global and local generator~

**Comment by ZJ9527** [comment]
hello,i met a qusetion when i run normalization.py,i try my best to solve it,but i failed,if you have some advice?
the following is my error
File "normalization.py", line 74, in <module>
    new_source_head, _ = get_scale(new_source[:,:,0])
  File "normalization.py", line 43, in get_scale
    head_x, height = linspace1[list(any1)][0], len(linspace1[list(any1)])
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by WilliammmZ** [comment]
In my mind, the line43's code try to find the height pixel of the image, calculate the height of the dancer and confirm the position of the head.  I think the problem may caused by the code in line70, please check the data  in 'new_source'. Thanks~
