### ISSUE TITLE
module 'torchvision.models.vgg' has no attribute 'cfg'

### ISSUE THREAD

**Issue by maveeshah** [yanx27/EverybodyDanceNow_reproduce_pytorch#86]
`self.vgg_features = vgg.make_layers(vgg.cfg['D'])
AttributeError: module 'torchvision.models.vgg' has no attribute 'cfg'`

File "./face_enhancer/main.py", line 68, in <module>
    main(is_debug)
  File "./face_enhancer/main.py", line 59, in main
    trainer = Trainer(ckpt_dir, log_dir, face_dataset, data_loader, log_every=1, save_every=1)
 File "face_enhancer/trainer.py", line 35, in __init__
    self.recon_loss = VGG_perceptual_loss(pretrained=True, device=self.device)
  File "/face_enhancer/utils/perceptual_loss.py", line 14, in __init__
    self.vgg_features = vgg.make_layers(vgg.cfg['D'])
AttributeError: module 'torchvision.models.vgg' has no attribute 'cfg'

**Comment by maveeshah** [comment]
it was solved by downgrading torchvision

pip install torchvision==0.2.2.post3

**Comment by WangYaC** [comment]
`self.vgg_features = vgg.make_layers([64, 64, 'M', 128, 128, 'M', 256, 256, 256, 'M', 512, 512, 512, 'M', 512, 512, 512, 'M'])`
[https://pytorch.org/vision/stable/_modules/torchvision/models/vgg.html](url)
works
