### ISSUE TITLE
About make dataset(source, target)

### ISSUE THREAD

**Issue by HeonKK** [yanx27/EverybodyDanceNow_reproduce_pytorch#87]
I want to use a video with only the upper body, but there is an error in make_source or make_target.

Bulding VGG19
  0%|                                                              | 0/1448 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "make_target.py", line 95, in <module>
    head_cord = cord[index]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "make_target.py", line 97, in <module>
    head_cord = pose_cords[-1] # if there is not head point in picture, use last frame
IndexError: list index out of range

How can I solve this problem?

**Comment by Ha0Tang** [comment]
+1

**Comment by HeonKK** [comment]
I solve this problem

head pose = pose_cords[ new index ] 

with check head image

**Comment by ManInBlackie** [comment]
@HeonKK I don't have head pose as a variable, and what do you mean by "with check head image"?

**Comment by HeonKK** [comment]
I change **make_source.py** and **make_target.py**

    **index = 7**
    crop_size = 25
    try:
        head_cord = cord[index]
    except:
        head_cord = pose_cords[-1] # if there is not head point in picture, use last frame


'check head image' means when this code can't find head pose cord I change index of cord and run this code.
Then check your face image which are face image in ./data/source(target)/test_head_ori.
